In [1]:
import numpy as np
a=np.array
print(a)

<built-in function array>


In [2]:
a=numpy.array([1,2,3])
print(a)

NameError: name 'numpy' is not defined

In [3]:
import numpy
a=numpy.array([1,2,3])
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
import numpy
a=numpy.array([1,2,3],[4,5,6])
print(a)

TypeError: data type not understood

In [6]:
a=numpy.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np
arr=np.array([1,2.,3.])
arr

array([1., 2., 3.])

In [4]:
arr=np.array([[1,2.,3.],[4.,5.,7]])
arr

array([[1., 2., 3.],
       [4., 5., 7.]])

In [7]:
a=numpy.array([1,3,5,7], dtype=complex)
print(a)

[1.+0.j 3.+0.j 5.+0.j 7.+0.j]


In [7]:
arr=np.array([12,45.,3.],dtype=complex)
arr

array([12.+0.j, 45.+0.j,  3.+0.j])

In [8]:
arr=numpy.array([[1,2,3,4],[4,5,6,7],[9,10,11,23]])
print(arr.ndim)

2


In [10]:
print(arr)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 23]]


In [6]:
arr=np.array([1,2.,3.],ndmin=2)
arr

array([[1., 2., 3.]])

In [1]:
#finding the size of each item in the array
import numpy as np
a=np.array([1,2,3])
print("Each item contains", a.itemsize, "bytes")

Each item contains 4 bytes


In [2]:
a=np.array([[1,2,3]])
print("Each item contains", a.itemsize, "bytes")

Each item contains 4 bytes


In [3]:
#finding the data type of each array item
import numpy as np
a=np.array([1,2,3])
print("Each item is of the type", a.dtype)

Each item is of the type int32


In [4]:
#finding the shape and size of the array
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print("Array Size:",a.size)
print("Array Shape:",a.shape)

Array Size: 7
Array Shape: (7,)


###### Reshaping the array objects

In [5]:
#Reshaping the array objects
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print("printing the original array..")
print(a)
print("printing the reshaped array..")
a=a.reshape(2,3)
print(a)

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


In [22]:
#C-like index ordering
x=np.arange(12)
y=np.reshape(x,(4,3))
x,y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [23]:
#Equivalent to C ravel then C reshape 
x=np.arange(12)
y=np.reshape(np.ravel(x),(3,4)) #Know more about ravel() function----google
x,y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [27]:
#Fortran-like index ordering
x=np.arange(12)
y=np.reshape(x,(4,3),order='F') 
x,y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

In [25]:
#Fortran-like index ordering
x=np.arange(12)
y=np.reshape(np.ravel(x, order='F'),(4,3), order='F') #Know more about ravel() function----google
x,y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

In [26]:
#The unspecified value is inferred to be 2
x=np.arange(12)
y=np.reshape(x,(2,-1)) #Doubt--??
x,y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]))

In [6]:
#Slicing in the Array
a=np.array([[1,2],[3,4],[5,6]])
print(a[0,1])
print(a[2,0])

2
5


In [8]:
#Linspace in the Array
a=np.linspace(5,15,10)#prints 10 values which are evenly spaced over the given interval 5-15
print(a)

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


In [9]:
#Finding the Maximum, Minimum, and Sum of the Array elements
a=np.array([1,2,3,10,15,4])
print("The array:",a)
print("The maximum element:",a.max())
print("The minimum element:",a.min())
print("The sum of the elements:",a.sum())

The array: [ 1  2  3 10 15  4]
The maximum element: 15
The minimum element: 1
The sum of the elements: 35


In [28]:
#numpy.sum()
a=np.array([0.4,0.5])
b=np.sum(a)
b

0.9

In [29]:
a=np.array([0.4,0.5,0.9,6.1])
x=np.sum(a,dtype=np.int32)
x

6

In [30]:
a=np.array([[1,4],[3,5]])
b=np.sum(a)
b

13

In [31]:
a=np.array([[1,4],[3,5]])
b=np.sum(a,axis=0)
b

array([4, 9])

In [32]:
a=np.array([[1,4],[3,5]])
b=np.sum(a,axis=1)
b

array([5, 8])

In [33]:
b=np.sum([15],initial=8)
b

23

In [10]:
#Numpy Array Axis ----- Very V. V. IMPortant Topic
a=np.array([[1,2,30],[10,15,4]])
print("The array:",a)
print("The maximum elements of columns:",a.max(axis=0))
print("The minimum elements of rows:",a.min(axis=1))
print("The sum of all rows:",a.sum(axis=1))

The array: [[ 1  2 30]
 [10 15  4]]
The maximum elements of columns: [10 15 30]
The minimum elements of rows: [1 4]
The sum of all rows: [33 29]


In [11]:
#Finding square root and standard deviation
a=np.array([[1,2,30],[10,15,4]])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]
10.044346115546242


In [12]:
#Arithmetic operations on the array
a=np.array([[1,2,30],[10,15,4]])
b=np.array([[1,2,3],[12,19,29]])
print("Sum of array a and b\n",a+b)
print("Product of array a and b\n",a*b)
print("Division of array a and b\n",a/b)

Sum of array a and b
 [[ 2  4 33]
 [22 34 33]]
Product of array a and b
 [[  1   4  90]
 [120 285 116]]
Division of array a and b
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [14]:
#Array Concatenation
a=np.array([[1,2,30],[10,15,4]])
b=np.array([[1,2,3],[12,19,29]])
print("Array vertically concatenated\n",np.vstack((a,b)))#np.vstack takes only 1 argument that's why (a,b) is written as 1 argument
print("Array horizontally concatenated\n",np.hstack((a,b)))#np.hstack takes only 1 argument that's why (a,b) is written as 1 argument

Array vertically concatenated
 [[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
Array horizontally concatenated
 [[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]


In [9]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[12,30]])
z=np.concatenate((x,y))
z

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [10]:
x=np.array([[1,2],[3,4]])
y=np.array([[12,30]])
z=np.concatenate((x,y),axis=0)
z

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [11]:
x=np.array([[1,2],[3,4]])
y=np.array([[12,30]])
z=np.concatenate((x,y.T),axis=1) # '.T' is used to change the rows into columns and columns into rows
z

array([[ 1,  2, 12],
       [ 3,  4, 30]])

In [12]:
x=np.array([[1,2],[3,4]])
y=np.array([[12,30]])
z=np.concatenate((x,y),axis=None)
z

array([ 1,  2,  3,  4, 12, 30])

In [20]:
x=np.ma.arange(3) #Know more about Masking-----KNow it(google)
y=np.arange(3,6)
x[1]=np.ma.masked
z1=np.concatenate([x,y])
z2=np.ma.concatenate([x,y])
x,y,z1,z2 #In last line only all results should be written together not on 1 after other in different lines*

(masked_array(data=[0, --, 2],
              mask=[False,  True, False],
        fill_value=999999),
 array([3, 4, 5]),
 masked_array(data=[0, 1, 2, 3, 4, 5],
              mask=False,
        fill_value=999999),
 masked_array(data=[0, --, 2, 3, 4, 5],
              mask=[False,  True, False, False, False, False],
        fill_value=999999))

In [15]:
#Numpy Datatypes
import numpy as np
d=np.dtype(np.int32)
print(d)

int32


In [18]:
d=np.int32(i4) #Doubt
print(d)

NameError: name 'i4' is not defined

In [19]:
#Creating a Structured data type
d=np.dtype([('salary',np.float)])
print(d)

[('salary', '<f8')]


In [22]:
d=np.dtype([('salary',np.float)])
arr=np.array([(10000.12,),(20000.50,)],dtype=d)
# OR #arr=np.array([10000.12,20000.50],dtype=d)
print(arr['salary'])# V. V. V. IMPortant

[10000.12 20000.5 ]


In [1]:
#1.numpy.empty
import numpy as np
arr=np.empty((3,2), dtype=int)
print(arr) #It creates random values in an array, How ??? #Doubt

[[-567934946       2046]
 [-567922080       2046]
 [   5439567         69]]


In [2]:
#2.numpy.Zeros
arr=np.zeros((3,2), dtype=int)
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [34]:
#numpy.zeros() without dtype and order
a=np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [35]:
#numpy.zeros() without order
a=np.zeros((6,),dtype=int)
a

array([0, 0, 0, 0, 0, 0])

In [36]:
#numpy.zeros() with shape
a=np.zeros((6,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
s1=(3,2)
a=np.zeros(s1)
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
#numpy.zeros() with custom dtype
a=np.zeros((3,), dtype=[('x','i4'),('y','i4')])
a

array([(0, 0), (0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [3]:
#3.numpy.ones
arr=np.ones((3,2), dtype=int)
print(arr)

[[1 1]
 [1 1]
 [1 1]]


In [4]:
#1.numpy.asarray
   
#Creating numpy array using the List
import numpy as np
l=[1,2,3,4,5,6,7]
a=np.asarray(l)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [6]:
#Creating a numpy array using Tuple
l=(1,2,3,4,5,6,7)
a=np.asarray(l); #Doubt in this ';' Syntax
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [2]:
#Creating a numpy array using more than one List
import numpy as np
l=[[1,2,3,4,5,6,7],[8,9]]
a=np.asarray(l)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[list([1, 2, 3, 4, 5, 6, 7]) list([8, 9])]


In [3]:
#2.numpy.frombuffer
l=b'hello world'
print(type(l))
a=np.frombuffer(l, dtype="S1") # "S1" --which type of datatype ????
print(a)
print(type(a))

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [4]:
#3.numpy.fromiter
list=[0,2,4,6]
it=iter(list) #it is the iterable object
x=np.fromiter(it, dtype=float) #Doubt #V. V. V. IMPortant
print(x)
print(type(x))

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [7]:
#1.numpy.arange #NOT .arrange
import numpy as np
arr=np.arange(0,10,2,float)# 2 is step or spacing of elements in their range/count
#arr=np.arrange(0,10,2,float) #np.arrange will give ERRor
print(arr)

[0. 2. 4. 6. 8.]


In [8]:
arr=np.arange(10,100,5,int)
print("The array over the given range is",arr)

The array over the given range is [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
#2.numpy.linspace
arr=np.linspace(10,20,5)
print("The array over the given range is",arr)

The array over the given range is [10.  12.5 15.  17.5 20. ]


In [10]:
arr=np.linspace(10,20,5,endpoint=False) #endpoint is 20 here which is bydefault True in above code
print("The array over the given range is",arr)

The array over the given range is [10. 12. 14. 16. 18.]


In [11]:
#3.numpy.logspace
arr=np.logspace(10,20,num=5,endpoint=True)
print("The array over the given range is",arr)

The array over the given range is [1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


In [12]:
arr=np.logspace(10,20,num=5,base=2,endpoint=True) #base represents base of log ---Doubt
print("The array over the given range is",arr)

The array over the given range is [1.02400000e+03 5.79261875e+03 3.27680000e+04 1.85363800e+05
 1.04857600e+06]
