In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
b=np.array([2,4,6,8,10,12,14,19])
c=a*b
print(c)

ValueError: operands could not be broadcast together with shapes (7,) (8,) 

In [3]:
a=np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b=np.array([2,4,6,8])
print("\nprinting array a..")
print(a)
print("\nprinting array b..")
print(b)
print("\n Adding arrays a and b ..")
c=a+b
print(c)


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

 Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [5]:
import numpy as np
a=np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
print("Print array:")
print(a)
print("Iterating over the array:")
for x in np.nditer(a):
    print(x,end=' ')

Print array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [7]:
#transpose of a matrix
a=np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
print("Printing array:")
print(a)
print("Printing the transpose of the array:")
at=a.T
print(at)

#this will be same as previous
for x in np.nditer(at):
    print(print("Iterating over the array:)")
for x in np.nditer(aa):
    print(x,end=' ')
          
#Doubt....

SyntaxError: invalid syntax (<ipython-input-7-e723a47fe270>, line 12)

In [ ]:
#Incomplete Numpy Array iteration

In [8]:
#1.bitwise_and Operation and Operator
import numpy as np
a=10
b=12

print("Binary representation of a:",bin(a))
print("Binary representation of a:",bin(b))
print("Bitwise-and of a and b:",np.bitwise_and(a,b))

Binary representation of a: 0b1010
Binary representation of a: 0b1100
Bitwise-and of a and b: 8


In [9]:
#2.bitwise_or Operator 
a=50
b=90
print("Binary representation of a:",bin(a))
print("Binary representation of a:",bin(b))
print("Bitwise-and of a and b:",np.bitwise_or(a,b))

Binary representation of a: 0b110010
Binary representation of a: 0b1011010
Bitwise-and of a and b: 122


In [10]:
#3.Invert Operation
arr=np.array([20], dtype=np.uint8)
print("Binary representation:",np.binary_repr(20,8))
print(np.invert(arr))
print("Binary representation:",np.binary_repr(235,8))

Binary representation: 00010100
[235]
Binary representation: 11101011


In [13]:
#Left Shift Operation with numpy.left_shift()
import numpy as np
print("left shift of 20 by 3 bits is",np.left_shift(20,3)) #V. V. IMP
print("Binary representation of 20 in 8 bits:",np.binary_repr(20,8))
print("Binary representation of 160 in 8 bits:",np.binary_repr(160,8))

left shift of 20 by 3 bits is 160
Binary representation of 20 in 8 bits: 00010100
Binary representation of 160 in 8 bits: 10100000


In [14]:
#Right Shift Operation with numpy.right_shift()
import numpy as np
print("left shift of 20 by 3 bits is",np.right_shift(20,3)) #V. V. IMP
print("Binary representation of 20 in 8 bits:",np.binary_repr(20,8))
print("Binary representation of 160 in 8 bits:",np.binary_repr(160,8))

left shift of 20 by 3 bits is 2
Binary representation of 20 in 8 bits: 00010100
Binary representation of 160 in 8 bits: 10100000


In [17]:
#1.numpy.char.add()
import numpy as np
print("Concatenating two string arrays:")
print(np.char.add(['welcome','Hi'],[' to Javatpoint',' read Python'])) #In 2nd array keep 1st element be '' to create space while adding the strings

Concatenating two string arrays:
['welcome to Javatpoint' 'Hi read Python']


In [19]:
#2.numpy.char.multiply()
import numpy as np
print("Printing a string multiple times:")
print(np.char.multiply("hello ",3))#keep Last element be '' in hello to create space while adding the strings

Printing a string multiple times:
hello hello hello 


In [20]:
#3.numpy.char.center()
print("Padding the string through left and right with the fill char *")
#np.char.center(string, width, fillchar)
print(np.char.center("Javatpoint",20,'*'))

Padding the string through left and right with the fill char *
*****Javatpoint*****


In [21]:
#4.numpy.char.capitalize()
print("Capitalizing the string using capitalize()...")
print(np.char.capitalize("welcome to javatpoint"))

Capitalizing the string using capitalize()...
Welcome to javatpoint


In [22]:
#5.numpy.char.title()
print("Converting string into title cased version...")
print(np.char.title("welcome to javatpoint"))

Converting string into title cased version...
Welcome To Javatpoint


In [23]:
#6.numpy.char.lower()
print("Converting all the characters of the string into lowercase...")
print(np.char.lower("WELCOME TO JAVATPOINT"))

Converting all the characters of the string into lowercase...
welcome to javatpoint


In [24]:
#7.numpy.char.upper()
print("Converting all the characters of the string into uppercase...")
print(np.char.upper("Welcome To Javatpoint"))

Converting all the characters of the string into uppercase...
WELCOME TO JAVATPOINT


In [3]:
#8.numpy.char.split()
import numpy as np
print("Splitting the String word by word..")
print(np.char.split("Welcome To Javatpoint"),sep="")#OR sep=" "

Splitting the String word by word..
['Welcome', 'To', 'Javatpoint']


In [4]:
#9.numpy.char.splitlines()
print("Splitting the String line by line..")
print(np.char.splitlines("Welcome\nTo\nJavatpoint"))#IMPortanTANce of this function----????

Splitting the String line by line..
['Welcome', 'To', 'Javatpoint']


In [5]:
#10.numpy.char.strip()
str="   welcome to javatpoint   "
print("Original String:\n",str)
print("Removing the leading and trailing whitespaces from the string")
print(np.char.strip(str))

Original String:
    welcome to javatpoint   
Removing the leading and trailing whitespaces from the string
welcome to javatpoint


In [6]:
#11.numpy.char.join()
print(np.char.join(':','HM')) #More Examples--??

H:M


In [8]:
#12.numpy.char.replace()
str="Welcome to Javapoint"
print("Original String:",str)
print("Modified String:",end=" ") #here space is given by 'end' at last of "Modified String"
print(np.char.replace(str, "Welcome to","www.")) #How replace operation has taken place--??

Original String: Welcome to Javapoint
Modified String: www. Javapoint


In [9]:
#13.numpy.char.encode() and decode()
enstr=np.char.encode("welcome to javatpoint",'cp500')
dstr=np.char.decode(enstr,'cp500')
print(enstr)
print(dstr)

b'\xa6\x85\x93\x83\x96\x94\x85@\xa3\x96@\x91\x81\xa5\x81\xa3\x97\x96\x89\x95\xa3'
welcome to javatpoint
