#### NumPy Other Functions

In [1]:
# numpy.append()

import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[11,21,31],[42,52,62],[73,83,93]])
c=np.append(a,b)
print(c)

[10 20 30 40 50 60 70 80 90 11 21 31 42 52 62 73 83 93]


In [2]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[11,21,31],[42,52,62],[73,83,93]])
c=np.append(a,b,axis=0)
print(c)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [11 21 31]
 [42 52 62]
 [73 83 93]]


In [2]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[11,21,31],[42,52,62],[73,83,93]])
c=np.append(a,b,axis=1)
c

array([[10, 20, 30, 11, 21, 31],
       [40, 50, 60, 42, 52, 62],
       [70, 80, 90, 73, 83, 93]])

###### numpy.random() functions

In [4]:
#1. np.random.rand(d0,d1,....,dn)
import numpy as np
a=np.random.rand(5,2)
print(a)

[[0.67248244 0.4227327 ]
 [0.10323554 0.77555382]
 [0.9204504  0.53868211]
 [0.92004215 0.28927698]
 [0.89328039 0.85970516]]


In [5]:
#2. np.random.randn(d0,d1,...,dn)
a=np.random.randn(2,2)
print(a)

[[ 0.93255776 -1.57603819]
 [ 1.0658079   2.37541383]]


In [7]:
#3. np.random.randint(low[,high,size,dtype])
a=np.random.randint(3,size=10)
print(a)

[2 1 2 0 1 0 0 0 0 0]


In [9]:
#4. np.random.random_integers(low[,high,size])
a=np.random.random_integers(3)
print(a)
b=type(np.random.random_integers(3))
print(b)
c=np.random.random_integers(5, size=(3,2))
print(c)

2
<class 'numpy.int32'>
[[5 5]
 [5 5]
 [1 1]]


C:\Users\user\anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  
C:\Users\user\anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  after removing the cwd from sys.path.
C:\Users\user\anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  


In [1]:
#5. np.random.random_sample([size])
import numpy as np
a=np.random.random_sample()
print(a)
b=type(np.random.random_sample())
print(b)
c=np.random.random_sample(5,)
print(c)

0.4342307849859538
<class 'float'>
[0.4192768  0.12159888 0.47448295 0.62952961 0.5881147 ]


In [2]:
#6. np.random.random([size])
a=np.random.random()
print(a)
b=type(np.random.random())
print(b)
c=np.random.random(5,)
print(c)

0.6078567779563742
<class 'float'>
[0.0255811  0.76298806 0.99453624 0.48168398 0.24704602]


In [3]:
#7. np.random.ranf([size])
a=np.random.ranf()
print(a)
b=type(np.random.ranf())
print(b)
c=np.random.ranf(5,)
print(c)

0.47594363998890854
<class 'float'>
[0.07298536 0.2912933  0.79942054 0.65692348 0.9882301 ]


In [4]:
#8. np.random.sample([size])
a=np.random.sample()
print(a)
b=type(np.random.sample())
print(b)
c=np.random.sample(5,)
print(c)

0.7957620440766205
<class 'float'>
[0.43651063 0.92402014 0.23474577 0.24824737 0.79131109]


In [6]:
#9. np.random.choice(a[,size, replace, p])
a=np.random.choice(5,3)
print(a)
b=np.random.choice(5,3, p=[0.2,0.1,0.4,0.2,0.1])
print(b)

[4 3 2]
[0 0 4]


In [9]:
#10. np.random.bytes(length)
a=np.random.bytes(7)
print(a)

b'\x9c\x92\xa6\xe79~p'


In [11]:
#1. np.random.shuffle()
import numpy as np
a=np.arange(12)
print(a)
a=np.random.shuffle(a)
print(a)# Doubt in output

[ 0  1  2  3  4  5  6  7  8  9 10 11]
None


In [12]:
#2. np.random.permutation()
a=np.random.permutation(12)
print(a)

[10  6 11  0  2  1  3  8  4  7  5  9]
