In [6]:
#A. Trigonometric functions

#1. numpy.arccos()
import numpy as np
arr=[0,0.3,-1]
print("Input array : \n",arr)
arccos_val=np.arccos(arr)
print("\nInverse cos value : \n",arccos_val)

Input array : 
 [0, 0.3, -1]

Inverse cos value : 
 [1.57079633 1.26610367 3.14159265]


In [7]:
#2. numpy.arcsin()
import numpy as np
import math
arr=[0,0.3,-1]
print("Input array : \n",arr)
arcsin=np.arcsin(arr)
print("\nInverse Sine values : \n",arcsin)

Input array : 
 [0, 0.3, -1]

Inverse Sine values : 
 [ 0.          0.30469265 -1.57079633]


In [8]:
#3. numpy.arctan()
arr=[0,0.3,-1]
print("Input array : \n",arr)
arctan_val=np.arctan(arr)
print("\nInverse tan values : \n",arctan_val)

Input array : 
 [0, 0.3, -1]

Inverse tan values : 
 [ 0.          0.29145679 -0.78539816]


In [8]:
#4. numpy.sin()
import numpy as np
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("sin Array:",end=" ")
sinarr=np.sin(arr)
print(sinarr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
sin Array: [ 0.          0.70710678 -1.          0.5       ]


In [7]:
#5. numpy.cos()
import numpy as np
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("cos Array:",end=" ")
cosarr=np.cos(arr)
print(cosarr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
cos Array: [ 1.00000000e+00  7.07106781e-01 -1.83697020e-16  8.66025404e-01]


In [5]:
#6. numpy.tan()
import numpy as np
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("tan Array:",end=" ")
tanarr=np.tan(arr)
print(tanarr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
tan Array: [0.00000000e+00 1.00000000e+00 5.44374645e+15 5.77350269e-01]


In [11]:
#7. numpy.sinh()
import numpy as np
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("sinh Array:",end=" ")
sinharr=np.sinh(arr)
print(sinharr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
sinh Array: [ 0.          0.86867096 55.6543976   0.54785347]


In [9]:
#8. numpy.cosh()
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("cosh Array:",end=" ")
cosharr=np.cosh(arr)
print(cosharr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
cosh Array: [ 1.          1.32460909 55.66338089  1.14023832]


In [10]:
#9. numpy.tanh()
import numpy as np
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("tanh Array:",end=" ")
tanharr=np.tanh(arr)
print(tanharr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
tanh Array: [0.         0.6557942  0.99983861 0.48047278]


In [13]:
#10. numpy.arcsinh()
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("arcsinh Array:",end=" ")
arcsinharr=np.arcsinh(arr)
print(arcsinharr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
tan Array: [0.         0.72122549 2.25441459 0.50221899]


In [12]:
#11. numpy.arccosh()
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("arccosh Array:",end=" ")
arccosharr=np.arccosh(arr)
print(arccosharr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
arccosh Array: [       nan        nan 2.23188925        nan]


C:\Users\user\anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in arccosh
  


In [15]:
#12. numpy.arctanh()
import math
arr=np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])
print("Input Array:",arr)
print("arctanh Array:",end=" ")
arctanharr=np.arctanh(arr)
print(arctanharr)

Input Array: [0.         0.78539816 4.71238898 0.52359878]
arctanh Array: [0.         1.05930617        nan 0.58128501]


C:\Users\user\anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in arctanh
  


In [1]:
# Examples of Trigonometric functions
import numpy as np
arr=np.array([0,30,60,90,120,150,180])
print("\nThe sin value of the angles",end="")
print(np.sin(arr*np.pi/180))
print("\nThe cosine value of the angles",end="")
print(np.cos(arr*np.pi/180))
print("\nThe tangent value of the angles",end="")
print(np.tan(arr*np.pi/180))


The sin value of the angles[0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]

The cosine value of the angles[ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]

The tangent value of the angles[ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [7]:
arr=np.array([0,30,60,90])

print("printing the sin values of different angles")
sinval=np.sin(arr*np.pi/180)
print(sinval)
print("printing the inverse of the sin")
cosec=np.arcsin(sinval)
print(cosec)
print("printing the values in degrees")
print(np.degrees(cosec))
print("\n")


print("printing the cos values of different angles")
cosval=np.cos(arr*np.pi/180)
print(cosval)
print("printing the inverse of the cos")
sec=np.arccos(cosval)
print(sec)
print("printing the values in degrees")
print(np.degrees(sec))
print("\n")


print("printing the tan values of different angles")
tanval=np.tan(arr*np.pi/180)
print(tanval)
print("printing the inverse of the tan")
cot=np.arctan(tanval)
print(cot)
print("printing the values in degrees")
print(np.degrees(cot))
print("\n")

printing the sin values of different angles
[0.        0.5       0.8660254 1.       ]
printing the inverse of the sin
[0.         0.52359878 1.04719755 1.57079633]
printing the values in degrees
[ 0. 30. 60. 90.]


printing the cos values of different angles
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
printing the inverse of the cos
[0.         0.52359878 1.04719755 1.57079633]
printing the values in degrees
[ 0. 30. 60. 90.]


printing the tan values of different angles
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]
printing the inverse of the tan
[0.         0.52359878 1.04719755 1.57079633]
printing the values in degrees
[ 0. 30. 60. 90.]




In [8]:
#B. Rounding Functions

# a)numpy.around()
import numpy as np
arr=np.array([12.202, 90.23120, 123.020, 23.202])
print("printing the original array values:",end="")
print(arr)
print("Array values rounded off to 2 decimal position",np.around(arr,2))#Doubt
print("Array values rounded off to -1 decimal position",np.around(arr,-1))#Doubt

printing the original array values:[ 12.202   90.2312 123.02    23.202 ]
Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]


In [9]:
# b)numpy.floor()
arr=np.array([12.202, 90.23120, 123.020, 23.202])
print(np.floor(arr))

[ 12.  90. 123.  23.]


In [23]:
arr=[0.23,0.09,1.2,1.24,9.99]
print("Input array:",arr)
r_arr=np.floor(arr) #difference between  np.floor(), np.rint() and np.trunc()---- ????
print("Output array:",r_arr)
arr2=[145.23,0.12,12.34,123]
print("Input array:",arr2)
r_arr2=np.floor(arr2) #difference between np.floor(), np.rint() and np.trunc()---- ????
print("Output array:",r_arr2)

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [0. 0. 1. 1. 9.]
Input array: [145.23, 0.12, 12.34, 123]
Output array: [145.   0.  12. 123.]


In [10]:
# c)numpy.ceil()
arr=np.array([12.202, 90.23120, 123.020, 23.202])
print(np.ceil(arr))

[ 13.  91. 124.  24.]


In [22]:
arr=[0.23,0.09,1.2,1.24,9.99]
print("Input array:",arr)
r_arr=np.ceil(arr) 
print("Output array:",r_arr)
arr2=[145.23,0.12,12.34,123]
print("Input array:",arr2)
r_arr2=np.ceil(arr2) 
print("Output array:",r_arr2)

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [ 1.  1.  2.  2. 10.]
Input array: [145.23, 0.12, 12.34, 123]
Output array: [146.   1.  13. 123.]


In [16]:
# d)numpy.fix()
arr=[0.23,0.09,1.2,1.24,9.99]
print("Input array:",arr)
r_arr=np.fix(arr)
print("Output array:",r_arr)#here 9 is neare to 0 than 10 therefore 9 is taken in last element 

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [0. 0. 1. 1. 9.]


In [17]:
# e)numpy.rint()
arr=[0.23,0.09,1.2,1.24,9.99]
print("Input array:",arr)
r_arr=np.rint(arr)
print("Output array:",r_arr)

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [ 0.  0.  1.  1. 10.]


In [19]:
# f)numpy.trunc()
arr=[0.23,0.09,1.2,1.24,9.99]
print("Input array:",arr)
r_arr=np.trunc(arr) #difference between np.rint() and np.trunc()---- ????
print("Output array:",r_arr)
arr2=[145.23,0.12,12.34,123]
print("Input array:",arr2)
r_arr2=np.trunc(arr2) #difference between np.rint() and np.trunc()---- ????
print("Output array:",r_arr2)

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [0. 0. 1. 1. 9.]
Input array: [145.23, 0.12, 12.34, 123]
Output array: [145.   0.  12. 123.]


In [11]:
#1.Finding the minimum and maximum elements from the array
import numpy as np
a=np.array([[2,10,20],[80,43,31],[22,43,10]])
print("The original array:\n")
print(a)
print("\nThe minimum element among the array:",np.amin(a))
print("\nThe maximum element among the array:",np.amax(a))

print("\nThe minimum element among the rows of array:",np.amin(a,0))
print("\nThe maximum element among the rows of array:",np.amax(a,0))

print("\nThe minimum element among the columns of array:",np.amin(a,1))
print("\nThe maximum element among the columns of array:",np.amax(a,1))

The original array:

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]

The minimum element among the array: 2

The maximum element among the array: 80

The minimum element among the rows of array: [ 2 10 10]

The maximum element among the rows of array: [80 43 31]

The minimum element among the columns of array: [ 2 31 10]

The maximum element among the columns of array: [20 80 43]


In [12]:
#2.numpy.ptp()
a=np.array([[2,10,20],[80,43,31],[22,43,10]])
print("The original array:\n",a)
print("\nptp value along axis 1:",np.ptp(a,1))
print("ptp value along axis 0:",np.ptp(a,0))

The original array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

ptp value along axis 1: [18 49 33]
ptp value along axis 0: [78 33 21]


In [14]:
#3.numpy.percentile()
a=np.array([[2,10,20],[80,43,31],[22,43,10]])
print("Array:\n",a)
print("\nPercentile along axis 0:",np.percentile(a,10,0))#Doubt
print("Percentile along axis 1:",np.percentile(a,10,1))#Doubt

Array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

Percentile along axis 0: [ 6.  16.6 12. ]
Percentile along axis 1: [ 3.6 33.4 12.4]


In [15]:
#4.Calculating median, mean, and average of array items
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",a)
print("\nMedian of array along axis 0:",np.median(a,0))
print("\nMean of array along axis 0:",np.mean(a,0))
print("\nAverage of array along axis 1:",np.average(a,1))

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Median of array along axis 0: [4. 5. 6.]

Mean of array along axis 0: [4. 5. 6.]

Average of array along axis 1: [2. 5. 8.]


In [24]:
# mean examples
a=np.array([[1,2],[3,4]])
b=np.mean(a)
print(b)
x=np.array([[5,6],[7,34]])
y=np.mean(x)
print(y)

2.5
13.0


In [25]:
a=np.array([[2,4],[3,5]])
b=np.mean(a,axis=0)
c=np.mean(a,axis=1)
print(b)
print(c)

[2.5 4.5]
[3. 4.]


In [26]:
a=np.zeros((2, 512*512), dtype=np.float32)
a[0,:]=23.0
a[1,:]=32.0
c=np.mean(a)
print(c)

27.5


In [27]:
a[0,:]=2.0
a[1,:]=0.2
c=np.mean(a)
print(c)
d=np.mean(a, dtype=np.float64)
print(d)

1.0999985
1.1000000014901161


###### Other Mathematical Functions

In [2]:
#numpy.log()
import numpy as np
a=np.array([2,4,6,3**8])
b=np.log(a)
c=np.log2(a)
d=np.log10(a)
a,b,c,d

(array([   2,    4,    6, 6561]),
 array([0.69314718, 1.38629436, 1.79175947, 8.78889831]),
 array([ 1.        ,  2.        ,  2.5849625 , 12.67970001]),
 array([0.30103   , 0.60205999, 0.77815125, 3.81697004]))

In [3]:
x=np.log([2,np.e,np.e**3,0])
x

C:\Users\user\anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([0.69314718, 1.        , 3.        ,       -inf])

In [4]:
#numpy.degrees()
import numpy as np
import math
arr=[0, math.pi/2, math.pi/4, math.pi/6]
print("Input array : \n",arr)
degval=np.degrees(arr)
print("\n Degree value : \n",degval)

Input array : 
 [0, 1.5707963267948966, 0.7853981633974483, 0.5235987755982988]

 Degree value : 
 [ 0. 90. 45. 30.]


In [5]:
#numpy.deg2rad()
import numpy as np
import math
arr=[0, math.pi/2, math.pi/4, math.pi/6]
print("Input array : \n",arr)
radval=np.deg2rad(arr)
print("\n Radian value : \n", radval)

Input array : 
 [0, 1.5707963267948966, 0.7853981633974483, 0.5235987755982988]

 Radian value : 
 [0.         0.02741557 0.01370778 0.00913852]


In [6]:
#numpy.hypot()
base=[10,2,5,50]
per=[3,10,23,6]
print("Input base array:",base)
print("Input perpendicular array:",per)
hyp=np.hypot(base,per)
print("hypotenuse",hyp)

Input base array: [10, 2, 5, 50]
Input perpendicular array: [3, 10, 23, 6]
hypotenuse [10.44030651 10.19803903 23.53720459 50.35871325]


In [7]:
base=np.random.rand(3,4)
per=np.random.rand(3,4)
print("Input base array:",base)
print("Input perpendicular array:",per)
hyp=np.hypot(base,per)
print("hypotenuse",hyp)

Input base array: [[0.55357699 0.01975655 0.49717425 0.94525417]
 [0.60813476 0.74253988 0.16637373 0.05117472]
 [0.79196607 0.79440153 0.86607038 0.17279249]]
Input perpendicular array: [[0.95156031 0.20531339 0.20523171 0.88562034]
 [0.17882415 0.12990385 0.07267998 0.39969684]
 [0.82257753 0.04538666 0.7929181  0.16792006]]
hypotenuse [[1.10086989 0.20626175 0.53786829 1.29531032]
 [0.63388166 0.75381727 0.18155604 0.40295958]
 [1.1418599  0.79569701 1.17422187 0.24094479]]


In [8]:
#numpy.rad2deg()
import numpy as np
import math
arr=[0, math.pi/2, math.pi/4, math.pi/6]
print("Input array : \n",arr)
degval=np.rad2deg(arr)
print("\n Degree value : \n", degval)

Input array : 
 [0, 1.5707963267948966, 0.7853981633974483, 0.5235987755982988]

 Degree value : 
 [ 0. 90. 45. 30.]


In [9]:
#numpy.radians()
arr=[0,30,60,90]
print("Input array : \n",arr)
radval=np.radians(arr)
print("\n Radian value : \n", radval)

Input array : 
 [0, 30, 60, 90]

 Radian value : 
 [0.         0.52359878 1.04719755 1.57079633]
