### NumPy Matrix Library 

In [1]:
#numpy.matlib.empty()
import numpy as np
import numpy.matlib
print(numpy.matlib.empty((3,3)))# How can random numbers get generated--??

[[1.072e-321 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 4.545e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


In [2]:
#numpy.matlib.zeros()
import numpy as np
import numpy.matlib
print(numpy.matlib.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#numpy.matlib.zeros()
import numpy as np
import numpy.matlib
print(numpy.matlib.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#numpy.matlib.ones()
import numpy as np
import numpy.matlib
print(numpy.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [5]:
#numpy.matlib.eye()
import numpy as np
import numpy.matlib
print(numpy.matlib.eye(n=3, M=3, k=0, dtype=int)) #k is index of diagonal(indexing of diagonal)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
#numpy.matlib.identity()
import numpy as np
import numpy.matlib
print(numpy.matlib.identity(5, dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [7]:
#numpy.matlib.rand()
import numpy as np
import numpy.matlib
print(numpy.matlib.rand(3,3))

[[0.21442229 0.29224657 0.37195722]
 [0.67034349 0.5500118  0.76834012]
 [0.00846828 0.87294542 0.63687014]]


### NumPy Linear Algebra

In [3]:
#numpy.dot()
import numpy as np
a=np.array([[100,200],[23,12]])
b=np.array([[10,20],[12,21]])
dot=np.dot(a,b)
dot

array([[3400, 6200],
       [ 374,  712]])

In [4]:
#numpy.vdot()
a=np.array([[100,200],[23,12]])
b=np.array([[10,20],[12,21]])
vdot=np.vdot(a,b)
vdot

5528

In [6]:
#numpy.inner()
a=np.array([1,2,3,4,5,6])
b=np.array([23,23,12,2,1,2])
inner=np.inner(a,b)
inner

130

In [7]:
#numpy.matmul()
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[23,23,12],[2,1,2],[7,8,9]])
mul=np.matmul(a,b)
mul

array([[ 48,  49,  43],
       [144, 145, 112],
       [240, 241, 181]])

In [8]:
#numpy determinant
#numpy.linalg.det()
a=np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [10]:
#numpy.linalg.solve()
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(np.linalg.solve(a,b))

[[1. 0.]
 [0. 1.]]


In [11]:
#numpy.linalg.inv()
a=np.array([[1,2],[3,4]])
print("Original array:\n",a)
b=np.linalg.inv(a)
print("Inverse:\n",b)

Original array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### NumPy Matrix Multiplication

In [15]:
#Ex.1: Element-wise matrix multiplication
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)
result=np.multiply(array1,array2)
result

array([[[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]]])

In [16]:
#Ex.2: Matrix product
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)
result=np.matmul(array1,array2)
result

array([[[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]])

In [17]:
#Ex.3: Dot Product
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)
result=np.dot(array1,array2)
result

array([[[[ 30,  24,  18]],

        [[ 84,  69,  54]],

        [[138, 114,  90]]]])